### PR TITLE
Gaussian and uniform RNGs are separated

### PR DESCRIPTION
**Pull request by peterwittek**
Please verify the correctness of the results and also do a quick benchmark if we lost anything in speed. I could not try the VSL version, but that should work too.

### CODE REVIEW

**Comment by PanPalitta** [comment]
I'm running the test on this version of the code. We should be able to compare this to the test I run for the nbproc discussion we had yesterday.

**Comment by PanPalitta** [comment]
Test from N=4 to N=24 shows no difference in speed with previous code. But there is segmentation fault at N=25.

**Comment by peterwittek** [comment]
Is this with VSL?

**Comment by PanPalitta** [comment]
No, this is with normal rng.

**Comment by peterwittek** [comment]
Well, then the segfault comes from somewhere else. In any case, please try it with VSL.

**Comment by PanPalitta** [comment]
I've tried testing the program using 5,6,10,12 processors and only the 6 and 12 processors produce segmentation fault as soon as the combination function is called. The 5-processor test runs smoothly, and the 10-processor test only produce segfault before the program exits (it's probably a problem with memory clean up). I've also isolated the part of the code in the combination that causes the segmentation fault, and it seems to be the part where the offspring is sent from my_rank = 0 to other processors. 

So it seems that the segfault problem either involve MPI in some form or has something to do with the candidate class, since it is the one that were extensively changed during the unit test. I will look more into detail about this later. For now I'll merge this version with master so we can continue to work on the code.

**Pull request merged**
